// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class ClientfirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL3GfCDwiqDGu48vJ8Y3cR_H7bHZ0kE0w',
    appId: '1:415789138972:web:58850d0fcdeb09b2284bd9',
    messagingSenderId: '415789138972',
    projectId: 'shoppingapp-2cad0',
    authDomain: 'shoppingapp-2cad0.firebaseapp.com',
    storageBucket: 'shoppingapp-2cad0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7-bm8dkM0taF6EokmVUfp5XT-63Nzazg',
    appId: '1:415789138972:android:99d91246d5dd1b94284bd9',
    messagingSenderId: '415789138972',
    projectId: 'shoppingapp-2cad0',
    storageBucket: 'shoppingapp-2cad0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl66CBd3nFarjcIc4jSVkWqxX9l1Z1e9k',
    appId: '1:415789138972:ios:bcca7fda6c49d682284bd9',
    messagingSenderId: '415789138972',
    projectId: 'shoppingapp-2cad0',
    storageBucket: 'shoppingapp-2cad0.firebasestorage.app',
    iosBundleId: 'com.example.cilentSide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl66CBd3nFarjcIc4jSVkWqxX9l1Z1e9k',
    appId: '1:415789138972:ios:bcca7fda6c49d682284bd9',
    messagingSenderId: '415789138972',
    projectId: 'shoppingapp-2cad0',
    storageBucket: 'shoppingapp-2cad0.firebasestorage.app',
    iosBundleId: 'com.example.cilentSide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL3GfCDwiqDGu48vJ8Y3cR_H7bHZ0kE0w',
    appId: '1:415789138972:web:dfab2472e0e07755284bd9',
    messagingSenderId: '415789138972',
    projectId: 'shoppingapp-2cad0',
    authDomain: 'shoppingapp-2cad0.firebaseapp.com',
    storageBucket: 'shoppingapp-2cad0.firebasestorage.app',
  );
}
